// This file was generated by utoipa-ts. Do not edit this file manually.

export type CreateTodo = { title: string, };

export type Todo = { id: string, title: string, done: boolean, };

export type UpdateTodo = { title: string | null, done: boolean | null, };

export type Api = {
  "GET /todos": {
    responses: {
      200: Array<Todo>;
    };
  };
  "POST /todos": {
    body: CreateTodo;
    responses: {
      201: Todo;
    };
  };
  "PUT /todos/{id}": {
    params: {
      id: string;
    };
    body: UpdateTodo;
    responses: {
      200: Todo;
      404: never;
    };
  };
};
