// This file was generated by utoipa-ts. Do not edit it manually.

export type CreateTodo = { title: string, };

export type Todo = { id: string, title: string, done: boolean, };

export type UpdateTodo = { title: string | null, done: boolean | null, };

export type Api = {
  "/todos": {
    GET: {
      responses: {
        /** @description Todo list */
        200: {
          body: Array<Todo>;
        };
      };
    };
    POST: {
      body: CreateTodo;
      responses: {
        /** @description Todo created */
        201: {
          body: Todo;
        };
      };
    };
  };
  "/todos/{id}": {
    PUT: {
      parameters: {
        path: {
          /** @description Todo ID */
          id: string;
        };
      };
      /** @description Todo fields to update */
      body: UpdateTodo;
      responses: {
        /** @description Todo updated */
        200: {
          body: Todo;
        };
        /** @description Todo not found */
        404: {
          body: never;
        };
      };
    };
  };
};
