// This file was generated by utoipa-ts. Do not edit it manually.

export type AccountStatus = "pending_invite" | "active" | "suspended";

export type CreateUser = { email: string, name: string, role: Role, tags: Array<string>, metadata: { [key in string]: string }, profile: UserProfile | null, };

export type ErrorCode = "bad_request" | "not_found" | "conflict" | "validation_failed";

export type ErrorResponse = { code: ErrorCode, message: string, requestId: string, issues: Array<ValidationIssue>, };

export type NotificationSettings = { emailEnabled: boolean, productUpdates: boolean, weeklyDigest: boolean, };

export type Role = "admin" | "editor" | "viewer";

export type SortOrder = "created_asc" | "created_desc" | "name_asc" | "name_desc";

export type UpdateUser = { email: string | null, name: string | null, role: Role | null, status: AccountStatus | null, tags: Array<string> | null, metadata: { [key in string]: string } | null, profile: UserProfile | null, notificationSettings: NotificationSettings | null, };

export type User = { id: string, email: string, name: string, role: Role, status: AccountStatus, tags: Array<string>, metadata: { [key in string]: string }, profile: UserProfile | null, notificationSettings: NotificationSettings, };

export type UserList = { items: Array<User>, total: bigint, page: number, perPage: number, hasNextPage: boolean, };

export type UserProfile = { display_name: string | null, bio: string | null, website: string | null, };

export type ValidationIssue = { field: string, message: string, };

export type Api = {
  "/users": {
    GET: {
      parameters: {
        query?: {
          /** @description Free-text search over user name and email. */
          q?: string;
          /** @description Filter users by role. */
          role?: Role;
          /** @description Filter users by account status. */
          status?: AccountStatus;
          /** @description Sort order for the result list. */
          sort?: SortOrder;
          /** @description Include suspended users in the result list. */
          includeSuspended?: boolean;
          /** @description Require users to have at least one of these tags. */
          tags?: string[];
          /** @description Page number starting from 1. */
          page?: number;
          /** @description Number of users to return per page. */
          perPage?: number;
        };
      };
      responses: {
        /** @description Users matching the supplied filters */
        200: {
          body: UserList;
          contentType: "application/json";
          headers: {
            /** @description Total number of users matching the filters */
            "x-total-count": string;
          };
        };
        /** @description Invalid query */
        400: {
          body: ErrorResponse;
        };
      };
    };
    POST: {
      /** @description User fields for a new account */
      body: CreateUser;
      responses: {
        /** @description User created */
        201: {
          body: User;
          contentType: "application/json";
          headers: {
            /** @description URL of the created user */
            location: string;
          };
        };
        /** @description Email already exists */
        409: {
          body: ErrorResponse;
        };
        /** @description Validation failed */
        422: {
          body: ErrorResponse;
        };
      };
    };
  };
  "/users/{id}": {
    DELETE: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description User deleted */
        204: {
          body: never;
        };
        /** @description User not found */
        404: {
          body: ErrorResponse;
        };
      };
    };
    GET: {
      parameters: {
        header: {
          /** @description Request correlation ID supplied by the client */
          "x-request-id": string;
        };
        path: {
          /** @description User ID */
          id: string;
        };
        cookie: {
          /** @description Session cookie used for this request */
          session_id: string;
        };
      };
      responses: {
        /** @description User found */
        200: {
          body: User;
        };
        /** @description User not found */
        404: {
          body: ErrorResponse;
        };
      };
    };
    PATCH: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      /** @description Partial user update */
      body: UpdateUser;
      responses: {
        /** @description User updated */
        200: {
          body: User;
        };
        /** @description User not found */
        404: {
          body: ErrorResponse;
        };
        /** @description Validation failed */
        422: {
          body: ErrorResponse;
        };
      };
    };
  };
};
