// This file was generated by utoipa-ts. Do not edit it manually.

export type CreateTodo = { title: string, };

export type MediaSize = "small" | "large" | "full" | "original";

export type SearchResults = { todos: Array<Todo>, };

export type Todo = { id: string, title: string, done: boolean, };

export type UpdateUser = { name: string, };

export type User = { id: string, name: string, };

export type Api = {
  "/search": {
    GET: {
      parameters: {
        query: {
          this: string;
          is?: number;
          cool?: string;
          wow?: number;
          size?: null | MediaSize;
        };
      };
      responses: {
        /** @description Search results */
        200: {
          body: SearchResults;
        };
        /** @description Bad request */
        400: {
          body: never;
        };
      };
    };
  };
  "/todos": {
    GET: {
      responses: {
        /** @description Todo list */
        200: {
          body: Array<Todo>;
        };
      };
    };
    POST: {
      body: CreateTodo;
      responses: {
        /** @description Todo created */
        201: {
          body: Todo;
        };
      };
    };
  };
  "/users/{id}": {
    GET: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description User found */
        200: {
          body: User;
        };
        /** @description User not found */
        404: {
          body: never;
        };
      };
    };
    PUT: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      /** @description Updated user fields */
      body: UpdateUser;
      responses: {
        /** @description User updated */
        200: {
          body: User;
        };
        /** @description User not found */
        404: {
          body: never;
        };
      };
    };
  };
};
