// This file was generated by utoipa-ts. Do not edit this file manually.

export type CreateTodo = { title: string, };

export type MediaSize = "small" | "large" | "full" | "original";

export type SearchResults = { todos: Array<Todo>, };

export type Todo = { id: string, title: string, done: boolean, };

export type UpdateUser = { name: string, };

export type User = { id: string, name: string, };

export type Api = {
  "GET /search": {
    params: {
      this: string;
      is?: number;
      cool?: string;
      wow?: number;
      size?: null | MediaSize;
    };
    responses: {
      200: SearchResults;
      400: never;
    };
  };
  "GET /todos": {
    responses: {
      200: Array<Todo>;
    };
  };
  "GET /users/{id}": {
    params: {
      id: string;
    };
    responses: {
      200: User;
      404: never;
    };
  };
  "POST /todos": {
    body: CreateTodo;
    responses: {
      201: Todo;
    };
  };
  "PUT /users/{id}": {
    params: {
      id: string;
    };
    body: UpdateUser;
    responses: {
      200: User;
      404: never;
    };
  };
};
